# Generated by Django 2.1.4 on 2019-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.TextField(blank=True, help_text='链接', null=True, verbose_name='链接'),
        ),
    ]
