# Generated by Django 2.1.4 on 2019-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pid',
            field=models.IntegerField(blank=True, help_text='关联ID', null=True, verbose_name='关联ID'),
        ),
    ]
