# Generated by Django 2.1.4 on 2019-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='top_img',
            field=models.ImageField(max_length=200, null=True, upload_to='user/'),
        ),
    ]
