# Generated by Django 2.1.4 on 2019-01-23 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='文章标题', max_length=100, verbose_name='文章标题')),
                ('img_src', models.CharField(blank=True, help_text='文章图片', max_length=300, null=True, verbose_name='文章图片')),
                ('content', models.TextField(default='', help_text='文章内容', verbose_name='文章内容')),
                ('thumbs_up_count', models.IntegerField(blank=True, help_text='点赞人数', null=True, verbose_name='点赞人数')),
                ('share_count', models.IntegerField(blank=True, help_text='分享次数', null=True, verbose_name='分享次数')),
                ('comment_count', models.IntegerField(blank=True, help_text='评论条数', null=True, verbose_name='评论条数')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
            },
        ),
    ]
