# Generated by Django 2.1.4 on 2019-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_blogarticle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='comment_count',
            field=models.IntegerField(blank=True, default=10, help_text='评论条数', null=True, verbose_name='评论条数'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='share_count',
            field=models.IntegerField(blank=True, default=10, help_text='分享次数', null=True, verbose_name='分享次数'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='thumbs_up_count',
            field=models.IntegerField(blank=True, default=10, help_text='点赞人数', null=True, verbose_name='点赞人数'),
        ),
    ]
