# Generated by Django 2.1.4 on 2019-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190124_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='is_hot',
            field=models.IntegerField(blank=True, default=0, help_text='是否热门', null=True, verbose_name='是否热门'),
        ),
    ]
