# Generated by Django 2.1.4 on 2019-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_blogarticle_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='desc',
            field=models.CharField(blank=True, help_text='文章简介', max_length=500, null=True, verbose_name='文章简介'),
        ),
    ]
