# Generated by Django 2.1.4 on 2019-01-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_blogarticle_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='markdown',
            field=models.TextField(default='', help_text='文章Markdown内容', verbose_name='文章Markdown内容'),
        ),
    ]
