# Generated by Django 2.1.4 on 2019-01-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190130_1019'),
        ('article', '0006_blogarticle_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='comment',
            field=models.ForeignKey(help_text='评论', null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', to_field='article_id', verbose_name='评论'),
        ),
    ]
