# Generated by Django 2.1.4 on 2019-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='category_type',
            field=models.CharField(blank=True, help_text='文章分类', max_length=20, null=True, verbose_name='文章分类'),
        ),
    ]
