# Generated by Django 2.1.4 on 2019-02-25 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_blogarticle_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticle',
            old_name='create_time',
            new_name='add_time',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间'),
        ),
    ]
