# Generated by Django 2.1.4 on 2019-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_blogarticle_look_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='article_type',
            field=models.IntegerField(choices=[(1, '技术'), (2, '随记')], default=2, help_text='文章类型', verbose_name='文章类型'),
            preserve_default=False,
        ),
    ]
