# Generated by Django 2.1.4 on 2019-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_blogarticle_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='article_type',
            field=models.IntegerField(choices=[(1, '技术'), (2, '随记')], default=1, help_text='文章类型', verbose_name='文章类型'),
        ),
    ]
