# Generated by Django 2.1.4 on 2019-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20190227_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='original',
            field=models.BooleanField(default=True, help_text='是否原创', verbose_name='是否原创'),
        ),
    ]
