# Generated by Django 2.1.4 on 2019-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_blogarticle_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='user',
        ),
    ]
