# Generated by Django 2.1.4 on 2019-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190221_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='images',
            field=models.ImageField(max_length=500, upload_to='article/'),
        ),
    ]
