# Generated by Django 2.1.4 on 2019-02-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20190221_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='images',
            new_name='image',
        ),
    ]
