# Generated by Django 2.1.4 on 2019-01-25 17:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='评论内容', null=True, verbose_name='评论内容')),
                ('comment_type', models.IntegerField(choices=[(1, '一级评论'), (2, '二级评论')], help_text='评论级别', verbose_name='评论级别')),
                ('thumbs_up_count', models.IntegerField(blank=True, default=10, help_text='点赞次数', null=True, verbose_name='点赞次数')),
                ('comment_time', models.DateTimeField(default=datetime.datetime.now, help_text='评论时间', verbose_name='评论时间')),
                ('parent', models.ForeignKey(blank=True, help_text='父评论ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.Comment', verbose_name='父评论ID')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
