# Generated by Django 2.1.4 on 2019-01-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.IntegerField(blank=True, help_text='文章ID', null=True, verbose_name='文章ID'),
        ),
    ]
