# Generated by Django 2.1.4 on 2019-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article_id',
            field=models.IntegerField(blank=True, help_text='文章ID', null=True, unique=True, verbose_name='文章ID'),
        ),
    ]
