# Generated by Django 2.1.4 on 2019-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190130_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article_id',
            field=models.IntegerField(blank=True, help_text='文章ID', null=True, verbose_name='文章ID'),
        ),
    ]
