# Generated by Django 2.1.4 on 2019-01-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190130_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article_id',
            field=models.ForeignKey(blank=True, help_text='文章ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.BlogArticle', verbose_name='文章ID'),
        ),
    ]
